# Manually created map from senator names in ../data/senator-transactions to senator names in ../data/senator-bill-embeddings
senator_name_map = {
    "A. Mitchell McConnell Jr.": "Mitch McConnell",
    "Jacklyn S Rosen": "Jacklyn Rosen",
    "John W Hickenlooper": "John Hickenlooper",
    "Mike Rounds": "Mike Rounds",
    "Sheldon Whitehouse": "Sheldon Whitehouse",
    "Angus S King Jr.": "Angus King",
    "James Banks": "Jim Banks",
    "Joseph Manchin III": "Joseph Manchin",
    "Pat Roberts": "Pat Roberts",
    "Shelley M Capito": "Shelley Capito",
    "Ashley Moody": "Ashley Moody",
    "James M Inhofe": "Jim Inhofe",
    "Katie Britt": "Katie Britt",
    "Patrick J Toomey": "Patrick Toomey",
    "Steve Daines": "Steve Daines",
    "Benjamin L Cardin": "Ben Cardin",
    "Jeanne Shaheen": "Jeanne Shaheen",
    "Kelly Loeffler": "Kelly  Loeffler",
    "Patty Murray": "Patty Murray",
    "Susan M Collins": "Susan Collins",
    "Bernie Moreno": "Bernie Moreno",
    "Jefferson B Sessions III": "Jefferson Sessions",
    "Ladda Tammy Duckworth": "Tammy Duckworth",
    "Rafael E Cruz": "Ted Cruz",
    "Tammy Duckworth": "Tammy Duckworth",
    "Chris Van Hollen": "Chris Van Hollen",
    "Jerry Moran": "Jerry Moran",
    "Lamar Alexander": "Lamar Alexander",
    "Rand Paul": "Rand Paul",
    "Thomas H Tuberville": "Tommy Tuberville",
    "Christopher A Coons": "Christopher Coons",
    "John A Barrasso": "John Barrasso",
    "Lindsey Graham": "Lindsey Graham",
    "Rick Scott": "Rick Scott",
    "Thomas R Carper": "Thomas Carper",
    "Cory A Booker": "Cory Booker",
    "John Boozman": "John Boozman",
    "Marco Rubio": "Marco Rubio",
    "Robert J Portman": "Rob Portman",
    "Thomas R Tillis": "Thomas Tillis",
    "Cynthia M Lummis": "Cynthia Lummis",
    "John Cornyn": "John Cornyn",
    "Maria Cantwell": "Maria Cantwell",
    "Robert P Casey Jr.": "Bob Casey",
    "Thomas Udall": "Tom Udall",
    "Daniel S Sullivan": "Dan Sullivan",
    "John F Reed": "John Reed",
    "Mark E Kelly": "Mark Kelly",
    "Roger F Wicker": "Roger Wicker",
    "Timothy M Kaine": "Timothy Kaine",
    "David A Perdue  Jr": "David Perdue",
    "John Fetterman": "John Fetterman",
    "Mark R Warner": "Mark Warner",
    "Roger W Marshall": "Roger Marshall",
    "Tina Smith": "Tina Smith",
    "David H McCormick": "David McCormick",
    "John Hoeven": "John Hoeven",
    "Markwayne Mullin": "Markwayne Mullin",
    "Ron Johnson": "Ron Johnson",
    "William Cassidy": "Bill Cassidy",
    "Debra S Fischer": "Deb Fischer",
    "John N Kennedy": "John Kennedy",
    "Michael  B Enzi": "Michael Enzi",
    "Ron L Wyden": "Ron Wyden",
    "William F Hagerty IV": "Bill Hagerty",
    "Gary C Peters": "Gary Peters",
    "John P Ricketts": "Pete Ricketts",
    "Michael D Crapo": "Michael Crapo",
    "Ron Wyden": "Ron Wyden",
    "JD Vance": "J. Vance",
    "John R Thune": "John Thune",
    "Michael F Bennet": "Michael Bennet",
    "Roy Blunt": "Roy Blunt"
}